# Nornir Default Connection Parameters

username: admin
password: cisco
platform: cisco_ios
port: 22

# Network device credentials
connection_options:
  netmiko:
    extras:
      device_type: cisco_ios
