# Nornir Inventory - Device Groups

# Test group - all lab/test devices
test:
  data:
    site: lab
    role: test

core:
  data:
    site: datacenter
    role: core

border:
  data:
    role: border

distribution:
  data:
    role: distribution

access:
  data:
    role: access

cisco_ios:
  platform: cisco_ios
  connection_options:
    netmiko:
      extras:
        device_type: cisco_ios

huawei_vrp:
  platform: huawei_vrp
  connection_options:
    netmiko:
      extras:
        device_type: huawei
